version: "2"

services:

    db:
        image: mdillon/postgis
        restart: on-failure
        environment:
            POSTGRES_USER: hipster
            POSTGRES_PASSWORD: notsostrong
            POSTGRES_DB: GoKiddo
        # volumes:
        #     - ./db/init/define.sql:/docker-entrypoint-initdb.d/z_define.sql
        # ports:
        #     - 5432:5432
        depends_on:
            - adminer

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080

    nginx:
        image: nginx:latest
        restart: on-failure
        # environment:
        ports:
            - 4000:80
            - 4001:443
        volumes:
            - ./app/build:/usr/share/nginx/www
            - ./images:/usr/share/nginx/images
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/ssl:/etc/nginx/ssl:ro
        depends_on:
            - api

    media:
        build: ./media
        restart: on-failure
        volumes:
            - ./images:/app/images

    mail:
        build: ./mail
        restart: on-failure

    api:
        build: ./api
        restart: on-failure
        depends_on:
            - db
            - media
            - mail

    app:
        build: ./app
        restart: on-failure
        # volumes:
            # - ./app/build:/app/build
        depends_on:
            - db
            - media
